export default [
  { name: 'HTML5', icon: 'https://www.vectorlogo.zone/logos/w3_html5/w3_html5-icon.svg' },
  { name: 'CSS', icon: 'https://www.vectorlogo.zone/logos/w3_css/w3_css-official.svg' },
  { name: 'ReactJS', icon: 'https://www.vectorlogo.zone/logos/reactjs/reactjs-icon.svg' },
  { name: 'Angular', icon: 'https://www.vectorlogo.zone/logos/angular/angular-icon.svg' },
  { name: 'Javascript', icon: 'https://www.vectorlogo.zone/logos/javascript/javascript-icon.svg' },
  { name: 'Typescript', icon: 'https://www.vectorlogo.zone/logos/typescriptlang/typescriptlang-icon.svg' },
  { name: 'Mocha', icon: 'https://www.vectorlogo.zone/logos/mochajs/mochajs-icon.svg' },
  { name: 'MUI', icon: 'https://www.vectorlogo.zone/logos/mui/mui-icon.svg' },
  { name: '.NET', icon: 'https://www.vectorlogo.zone/logos/dotnet/dotnet-official.svg' },
  { name: 'NUnit', icon: null },
  { name: 'Node', icon: 'https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg' },
  { name: 'SQL Server', icon: 'https://raw.githubusercontent.com/pheralb/svgl/refs/heads/main/static/library/sql-server.svg' },
  { name: 'MySQL', icon: 'https://www.vectorlogo.zone/logos/mysql/mysql-icon.svg' },
  { name: 'MongoDB', icon: 'https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg' },
  { name: 'PostgreSQL', icon: 'https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg' },
  { name: 'Redis', icon: 'https://www.vectorlogo.zone/logos/redis/redis-icon.svg' },
  { name: 'Jenkins', icon: 'https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg' },
  { name: 'Bitbucket', icon: 'https://www.vectorlogo.zone/logos/bitbucket/bitbucket-icon.svg' },
  { name: 'Git', icon: 'https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg' },
  { name: 'AWS', icon: 'https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-icon.svg' },
  { name: 'Azure', icon: 'https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg' },
  { name: 'ELK', icon: 'https://www.vectorlogo.zone/logos/elastic/elastic-icon.svg' },
  { name: 'Docker', icon: 'https://www.vectorlogo.zone/logos/docker/docker-tile.svg' },
  { name: 'Kubernetes', icon: 'https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg' },
  { name: 'Postman', icon: 'https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg' }
]